vim9script

# Cursor shape
# when start insert mode, set cursor to steady bar
&t_SI = "\<Esc>[6 q"
# when start replace mode, set cursor to steady block
&t_SR = "\<Esc>[2 q"
# when end insert mode, or replace mode, set cursor to steady block
&t_EI = "\<Esc>[2 q"
# when entering vim (terminal init), set cursor to steady block
# (concatenate the escape code to existing value)
&t_TI ..= "\<Esc>[2 q"
# when leaving vim (terminal exit), restore the cursor shape to terminal default configured by user
# (concatenate the escape code to existing value)
&t_TE ..= "\<Esc>[0 q"

# syntax highlight
syntax enable

# always show the status line at bottom
set laststatus=2

# make search case-insensitive, and but become case-sensitive if it contains any upper-case letter
set ignorecase
set smartcase

# incremental search
set incsearch

# enable mouse in all modes
set mouse=a

# tab and shift (<<, >>), backspace with 4 spaces
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

# do not generate backup file, undo file, swap file
set nobackup
set noundofile
set noswapfile

# no beep and flash when error
set noerrorbells
set novisualbell
set vb t_vb=

# autocomplete (insert and cmdline)
set autocomplete
set completeopt=menu,popup,noselect
set complete=o,.,w,b,u,t

set wildmenu
set wildmode=noselect:lastused,full
set wildoptions=pum,fuzzy,tagfile

# guicursor
set guicursor=n-v-c:block,i-c-ci-ve:ver25,r-cr:block,o:hor20,a:blinkon0-Cursor

# color
set termguicolors
colorscheme shine

g:mapleader = " "

# insert to normal mode
inoremap jj <Esc>
inoremap jk <C-o>

# goto line start, end
noremap H ^
noremap L $

# save file
noremap <Leader>w <Cmd>w<CR>

# up/down 5 lines
noremap <C-j> 5j
noremap <C-k> 5k

# clear highlight
noremap <Leader>c <Cmd>nohlsearch<CR>

# copy/paste
noremap <Leader>y "+y
noremap <Leader>p "+p

# quit
noremap <C-q> <Cmd>quit<CR>
